<?xml version="1.0"?>
<!-- This XSL transformation is used for generating DUCK config file for EmuDAQ and EmuDQM from a DAQ/DQM XDAQ configuration XML. -->
<!-- Usage example:  -->
<!--     xsltproc <hyphen><hyphen>stringparam DIR '/nfshome0/cscdaq/config/daq' <hyphen><hyphen>stringparam NAME 'DAQConfig' <hyphen><hyphen>stringparam FARM 'DAQ' lDAQDUCKGenerator.xsl <XDAQ_config_file.xml> > DAQ.duck -->
<xsl:transform xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns:xc="http://xdaq.web.cern.ch/xdaq/xsd/2004/XMLConfiguration-30"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
  xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/">

  <xsl:param name="SIDE">
    <xsl:if test="count( //xc:Application[@class='EmuMonitor' and number(@instance) &lt;= 18 ] ) > 0 and count( //xc:Application[@class='EmuMonitor' and number(@instance) > 18 ] ) = 0 ">P</xsl:if>
    <xsl:if test="count( //xc:Application[@class='EmuMonitor' and number(@instance) &lt;= 18 ] ) = 0 and count( //xc:Application[@class='EmuMonitor' and number(@instance) > 18 ] ) > 0 ">M</xsl:if>
  </xsl:param>

  <!-- Parameter DIR is to be set from the command line. -->
  <!-- It's the system directory containing the XDAQ configuration files. -->
  <xsl:param name="DIR">/nfshome0/cscdaq/config/daq</xsl:param>

  <!-- Parameter NAME is to be set from the command line. -->
  <!-- It's the name of the XDAQ configuration file (without path or extension) -->
  <xsl:param name="NAME"/>

  <!-- Parameter FARM is to be set from the command line. -->
  <!-- It's either DAQ or DQM or DQM_Display-->
  <xsl:param name="FARM"/>

  <xsl:param name="XDAQ_ZONE">emu</xsl:param>
  <!-- <xsl:param name="XDAQ_ZONE">emu904</xsl:param> -->

  <xsl:param name="CONFIG_FILE"><xsl:value-of select="$DIR"/>/<xsl:value-of select="$NAME"/>.xml</xsl:param>
  <xsl:param name="FM_CONFIG_PATH">
    <xsl:if test="$FARM='DAQ'">DAQ/<xsl:value-of select="$NAME"/></xsl:if>
    <xsl:if test="$FARM='DQM'">DQM/DQM<xsl:if test="$SIDE='P' or $SIDE='M'">_side<xsl:value-of select="$SIDE"/></xsl:if></xsl:if>
    <xsl:if test="$FARM='DQM_Display'">DQM/DQM_Display</xsl:if>
  </xsl:param>
  <!-- <xsl:param name="PATHTOEXECUTIVE">/opt/xdaq/bin/xdaq.exe</xsl:param> -->
  <xsl:param name="PATHTOEXECUTIVE">/opt/xdaq/share/<xsl:value-of select="$XDAQ_ZONE"/>/scripts/xdaq_autorestart.sh</xsl:param>

  <xsl:param name="DAQ_ENVIRONMENTSTRING">HOME=/nfshome0/cscdaq BUILD_HOME=/nfshome0/cscdaq/EmuLib/14/TriDAS XDAQ_ROOT=/opt/xdaq XDAQ_OS=linux XDAQ_PLATFORM=x86_64_cc7 XDAQ_DOCUMENT_ROOT=/opt/xdaq/htdocs XDAQ_SETUP_ROOT=/opt/xdaq/share ROOTSYS=/opt/cern/root_v6.12.06 DQMCONFIG=/nfshome0/cscdaq/config/dqm LD_LIBRARY_PATH=/opt/cern/root_v6.12.06/lib:/opt/xdaq/lib XDAQ_ZONE=<xsl:value-of select="$XDAQ_ZONE"/> XDAQ_PROFILE=/opt/xdaq/share/<xsl:value-of select="$XDAQ_ZONE"/>/profile/emu.profile PATH=/bin:/usr/bin</xsl:param>

  <xsl:param name="DQM_ENVIRONMENTSTRING">HOME=/nfshome0/cscdqm BUILD_HOME=/nfshome0/cscdqm/EmuLib/14/TriDAS XDAQ_ROOT=/opt/xdaq XDAQ_OS=linux XDAQ_PLATFORM=x86_64_cc7 XDAQ_DOCUMENT_ROOT=/opt/xdaq/htdocs XDAQ_SETUP_ROOT=/opt/xdaq/share ROOTSYS=/opt/cern/root_v6.12.06 DQMCONFIG=/nfshome0/cscdqm/config/dqm LD_LIBRARY_PATH=/opt/cern/root_v6.12.06/lib:/opt/xdaq/lib XDAQ_ZONE=<xsl:value-of select="$XDAQ_ZONE"/> XDAQ_PROFILE=/opt/xdaq/share/<xsl:value-of select="$XDAQ_ZONE"/>/profile/emu.profile PATH=/bin:/usr/bin</xsl:param>

  <!-- <xsl:param name="DAQ_ENVIRONMENTSTRING">HOME=/nfshome0/cscdaq BUILD_HOME=/nfshome0/cscdaq/EmuLib/14/TriDAS XDAQ_ROOT=/opt/xdaq XDAQ_OS=linux XDAQ_PLATFORM=x86_64_cc7 XDAQ_DOCUMENT_ROOT=/opt/xdaq/htdocs XDAQ_SETUP_ROOT=/opt/xdaq/share ROOTSYS=/opt/cern/root_v6.12.06 DQMCONFIG=/nfshome0/cscdaq/config/dqm LD_LIBRARY_PATH=/opt/cern/root_v6.12.06/lib:/nfshome0/cscdaq/EmuLib/14/TriDAS/x86_64_cc7/lib:/opt/xdaq/lib XDAQ_ZONE=<xsl:value-of select="$XDAQ_ZONE"/> XDAQ_PROFILE=/opt/xdaq/share/<xsl:value-of select="$XDAQ_ZONE"/>/profile/emu.profile PATH=/bin:/usr/bin</xsl:param> -->

  <!-- <xsl:param name="DQM_ENVIRONMENTSTRING">HOME=/nfshome0/cscdqm BUILD_HOME=/nfshome0/cscdqm/EmuLib/14/TriDAS XDAQ_ROOT=/opt/xdaq XDAQ_OS=linux XDAQ_PLATFORM=x86_64_cc7 XDAQ_DOCUMENT_ROOT=/opt/xdaq/htdocs XDAQ_SETUP_ROOT=/opt/xdaq/share ROOTSYS=/opt/cern/root_v6.12.06 DQMCONFIG=/nfshome0/cscdqm/config/dqm LD_LIBRARY_PATH=/opt/cern/root_v6.12.06/lib:/nfshome0/cscdqm/EmuLib/14/TriDAS/x86_64_cc7/lib:/opt/xdaq/lib XDAQ_ZONE=<xsl:value-of select="$XDAQ_ZONE"/> XDAQ_PROFILE=/opt/xdaq/share/<xsl:value-of select="$XDAQ_ZONE"/>/profile/emu.profile PATH=/bin:/usr/bin</xsl:param> -->

  <xsl:output method="xml" indent="yes"/>

  <!-- Generate DUCK files for EmuDAQ and EmuDQM -->
  <xsl:template match="xc:Partition">
    <xsl:comment>Generated by lDAQDUCKGenerator.xsl from <xsl:value-of select="$CONFIG_FILE"/></xsl:comment>
    <Configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" user="cscpro" path="{$FM_CONFIG_PATH}">
      <!-- <FunctionManager name="config" hostname="cmsrc-csc.cms" port="12000" -->
      <!-- 		       qualifiedResourceType="rcms.fm.resource.qualifiedresource.FunctionManager" -->
      <!-- 		       sourceURL="http://cmsrc-csc.cms:12000/functionmanagers/cscLevelOneFM.jar" -->
      <!-- 		       className="rcms.fm.app.cscLevelOne.MyFunctionManager" -->
      <!-- 		       role="CSC" > -->
      <FunctionManager name="config" hostname="cmsrc-csc.cms" port="12000"
		       qualifiedResourceType="rcms.fm.resource.qualifiedresource.FunctionManager"
		       sourceURL="http://cmsrc-csc.cms:12000/functionmanagers/CSCL1FM.jar"
		       className="rcms.fm.ajaxFM.MyFunctionManager"
		       role="CSC" >
	<!-- This takes too long, and RCMS times out:	<property name="pathToOrphanHandler" type="String"> -->
	<!-- 	  <value>/opt/xdaq/share/<xsl:value-of select="$XDAQ_ZONE"/>/scripts/killOrphanedXDAQ.sh</value> -->
	<!-- 	</property> -->

	<xsl:comment>JobControls</xsl:comment>
	<xsl:apply-templates select="//xc:Context"/>

	<xsl:if test="$FARM='DAQ'">
	  <xsl:apply-templates select="//xc:Application[@class='emu::ldaq::manager::Application' or @class='emu::ldaq::rui::Application' or @class='evb::EVM' or @class='evb::RU' or @class='evb::BU']"/>
	</xsl:if>

	<xsl:if test="$FARM='DQM'">
	  <xsl:apply-templates select="//xc:Application[@class='EmuMonitor']"/>
	</xsl:if>

	<xsl:if test="$FARM='DQM_Display'">
	  <xsl:apply-templates select="//xc:Application[@class='EmuDisplayClient']"/>
	</xsl:if>

      </FunctionManager>
    </Configuration>
  </xsl:template>


  <!-- JobControl, one per host -->
  <xsl:template match="xc:Context">
    <xsl:variable name="HTTP_HOST"><xsl:value-of select="substring-before( substring-after( @url, 'http://' ), ':' )"/></xsl:variable>
    <xsl:if test="count( preceding-sibling::xc:Context[ substring-before( substring-after( @url, 'http://' ), ':' ) = $HTTP_HOST ] ) = 0">
      <Service name="JobControl" hostname="{$HTTP_HOST}" port="9999" urn="urn:xdaq-application:lid=10" qualifiedResourceType="rcms.fm.resource.qualifiedresource.JobControl"/>
    </xsl:if>
  </xsl:template>

  <!-- emu::ldaq::manager::Application -->
  <xsl:template match="xc:Application[@class='emu::ldaq::manager::Application']">
    <xsl:variable name="HTTP_HOST"><xsl:value-of select="substring-before( substring-after( ../@url, 'http://' ), ':' )"/></xsl:variable>
    <xsl:variable name="HTTP_PORT"><xsl:value-of select="substring-after( ../@url, concat( $HTTP_HOST, ':' ) )"/></xsl:variable>
    <xsl:comment><xsl:value-of select="@class"/> <xsl:value-of select="@instance"/></xsl:comment>
    <XdaqExecutive hostname="{$HTTP_HOST}" port="{$HTTP_PORT}"
		   urn="urn:xdaq-application:lid=0"
		   qualifiedResourceType="rcms.fm.resource.qualifiedresource.XdaqExecutive"
		   instance="0"
		   pathToExecutive="{$PATHTOEXECUTIVE}"
		   unixUser="cscdaq"
		   logLevel="WARN"
		   logURL="file:/tmp/xdaq-daqmanager-cscdaq.log"
		   environmentString="{$DAQ_ENVIRONMENTSTRING}">
      <configFile location="file"><xsl:value-of select="$CONFIG_FILE"/></configFile>
    </XdaqExecutive>
    <XdaqApplication className="{@class}" hostname="{$HTTP_HOST}" port="{$HTTP_PORT}"
		     urn="urn:xdaq-application:lid={@id}"
		     qualifiedResourceType="rcms.fm.resource.qualifiedresource.XdaqApplication"
		     instance="0" />
  </xsl:template>

  <!-- emu::ldaq::rui::Application -->
  <xsl:template match="xc:Application[@class='emu::ldaq::rui::Application']">
    <xsl:variable name="HTTP_HOST"><xsl:value-of select="substring-before( substring-after( ../@url, 'http://' ), ':' )"/></xsl:variable>
    <xsl:variable name="HTTP_PORT"><xsl:value-of select="substring-after( ../@url, concat( $HTTP_HOST, ':' ) )"/></xsl:variable>
    <xsl:comment><xsl:value-of select="@class"/> <xsl:value-of select="@instance"/></xsl:comment>
    <XdaqExecutive hostname="{$HTTP_HOST}" port="{$HTTP_PORT}"
		   urn="urn:xdaq-application:lid=0"
		   qualifiedResourceType="rcms.fm.resource.qualifiedresource.XdaqExecutive"
		   instance="0"
		   pathToExecutive="{$PATHTOEXECUTIVE}"
		   unixUser="cscdaq"
		   logLevel="WARN"
		   logURL="file:/tmp/xdaq-rui{@instance}-cscdaq.log"
		   environmentString="{$DAQ_ENVIRONMENTSTRING}">
      <configFile location="file"><xsl:value-of select="$CONFIG_FILE"/></configFile>
    </XdaqExecutive>
  </xsl:template>

  <!-- evb::RU and evb::EVM -->
  <xsl:template match="xc:Application[@class='evb::RU' or @class='evb::EVM']">
    <xsl:variable name="HTTP_HOST"><xsl:value-of select="substring-before( substring-after( ../@url, 'http://' ), ':' )"/></xsl:variable>
    <xsl:variable name="HTTP_PORT"><xsl:value-of select="substring-after( ../@url, concat( $HTTP_HOST, ':' ) )"/></xsl:variable>
    <xsl:comment><xsl:value-of select="@class"/> <xsl:value-of select="@instance"/></xsl:comment>
    <XdaqExecutive hostname="{$HTTP_HOST}" port="{$HTTP_PORT}"
		   urn="urn:xdaq-application:lid=0"
		   qualifiedResourceType="rcms.fm.resource.qualifiedresource.XdaqExecutive"
		   instance="0"
		   pathToExecutive="{$PATHTOEXECUTIVE}"
		   unixUser="cscdaq"
		   logLevel="WARN"
		   logURL="file:/tmp/xdaq-ru{@instance}-cscdaq.log"
		   environmentString="{$DAQ_ENVIRONMENTSTRING}">
      <configFile location="file"><xsl:value-of select="$CONFIG_FILE"/></configFile>
    </XdaqExecutive>
  </xsl:template>

  <!-- evb::BU -->
  <xsl:template match="xc:Application[@class='evb::BU']">
    <xsl:variable name="HTTP_HOST"><xsl:value-of select="substring-before( substring-after( ../@url, 'http://' ), ':' )"/></xsl:variable>
    <xsl:variable name="HTTP_PORT"><xsl:value-of select="substring-after( ../@url, concat( $HTTP_HOST, ':' ) )"/></xsl:variable>
    <xsl:comment><xsl:value-of select="@class"/><xsl:value-of select="@instance"/></xsl:comment>
    <XdaqExecutive hostname="{$HTTP_HOST}" port="{$HTTP_PORT}"
		   urn="urn:xdaq-application:lid=0"
		   qualifiedResourceType="rcms.fm.resource.qualifiedresource.XdaqExecutive"
		   instance="0"
		   pathToExecutive="{$PATHTOEXECUTIVE}"
		   unixUser="cscdaq"
		   logLevel="WARN"
		   logURL="file:/tmp/xdaq-bu{@instance}-cscdaq.log"
		   environmentString="{$DAQ_ENVIRONMENTSTRING}">
      <configFile location="file"><xsl:value-of select="$CONFIG_FILE"/></configFile>
    </XdaqExecutive>
  </xsl:template>

  <!-- EmuDisplayClient -->
  <xsl:template match="xc:Application[@class='EmuDisplayClient']">
    <xsl:variable name="HTTP_HOST"><xsl:value-of select="substring-before( substring-after( ../@url, 'http://' ), ':' )"/></xsl:variable>
    <xsl:variable name="HTTP_PORT"><xsl:value-of select="substring-after( ../@url, concat( $HTTP_HOST, ':' ) )"/></xsl:variable>
    <xsl:comment><xsl:value-of select="@class"/> <xsl:value-of select="@instance"/></xsl:comment>
    <XdaqExecutive hostname="{$HTTP_HOST}" port="{$HTTP_PORT}"
		   urn="urn:xdaq-application:lid=0"
		   qualifiedResourceType="rcms.fm.resource.qualifiedresource.XdaqExecutive"
		   instance="0"
		   pathToExecutive="{$PATHTOEXECUTIVE}"
		   unixUser="cscdqm"
		   logLevel="WARN"
		   logURL="file:/tmp/xdaq-{@class}-cscdqm.log"
		   environmentString="{$DQM_ENVIRONMENTSTRING}">
      <configFile location="file"><xsl:value-of select="$CONFIG_FILE"/></configFile>
    </XdaqExecutive>
    <XdaqApplication className="{@class}" hostname="{$HTTP_HOST}" port="{$HTTP_PORT}"
		     urn="urn:xdaq-application:lid={@id}"
		     qualifiedResourceType="rcms.fm.resource.qualifiedresource.XdaqApplication"
		     instance="0" />
  </xsl:template>

  <!-- EmuMonitor -->
  <xsl:template match="xc:Application[@class='EmuMonitor']">
    <xsl:variable name="HTTP_HOST"><xsl:value-of select="substring-before( substring-after( ../@url, 'http://' ), ':' )"/></xsl:variable>
    <xsl:variable name="HTTP_PORT"><xsl:value-of select="substring-after( ../@url, concat( $HTTP_HOST, ':' ) )"/></xsl:variable>
    <xsl:comment><xsl:value-of select="@class"/><xsl:value-of select="@instance"/></xsl:comment>
    <XdaqExecutive hostname="{$HTTP_HOST}" port="{$HTTP_PORT}"
		   urn="urn:xdaq-application:lid=0"
		   qualifiedResourceType="rcms.fm.resource.qualifiedresource.XdaqExecutive"
		   instance="0"
		   pathToExecutive="{$PATHTOEXECUTIVE}"
		   unixUser="cscdqm"
		   logLevel="WARN"
		   logURL="file:/tmp/xdaq-EmuMonitor{@instance}-cscdqm.log"
		   environmentString="{$DQM_ENVIRONMENTSTRING}">
      <configFile location="file"><xsl:value-of select="$CONFIG_FILE"/></configFile>
    </XdaqExecutive>
  </xsl:template>

</xsl:transform>
