<?xml version="1.0"?>
<!-- This XSL transformation is used to generate XDAQ config file for EmuDAQ from a RUI-to-computer mapping. -->
<!-- Usage example:  -->
<!--     xsltproc [<hyphen><hyphen>stringparam SIDE 'P|M|B'] [<hyphen><hyphen>stringparam MASTERRUI '1'] <hyphen><hyphen>stringparam WRITE Y <hyphen><hyphen>stringparam BUILD N EmuDAQConfigGenerator.xsl RUI-to-computer_mapping.xml > DAQ.xml -->
<xsl:transform xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns:xc="http://xdaq.web.cern.ch/xdaq/xsd/2004/XMLConfiguration-30"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
  xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/">

  <!-- Parameter SIDE is to be optionally set from the command line. -->
  <!-- If it's set to 'M', only the minus side will be generated; if 'P', only the plus side; if 'B', both sides; otherwise both sides. -->
  <xsl:param name="SIDE"/>
  <!-- Parameter WRITE is to be set from the command line. -->
  <!-- If it is set to 'Y', the RUIs will write data to files; if 'N', they will not. -->
  <xsl:param name="WRITE"/>
  <!-- Parameter BUILD is to be set from the command line. -->
  <!-- If it is set to 'Y', events will be built; if 'N', events will not be built. -->
  <xsl:param name="BUILD"/>
  <!-- Parameter MASTERRUI is to be optionally set from the command line. -->
  <!-- It is the instance number of the RUI that is to send its data to the EVM. It's 19 by default if the plus side is not included, and 1 otherwise -->
  <xsl:param name="MASTERRUI">
    <xsl:choose>
      <xsl:when test="$SIDE='M'">19</xsl:when>
      <xsl:otherwise>1</xsl:otherwise>
    </xsl:choose>
  </xsl:param>

  <!-- <xsl:param name="EMULIBDIR">${BUILD_HOME}/${XDAQ_PLATFORM}/lib</xsl:param> -->
  <xsl:param name="EMULIBDIR">${XDAQ_ROOT}/lib</xsl:param>
  <xsl:param name="XDAQLIBDIR">${XDAQ_ROOT}/lib</xsl:param>

  <xsl:output method="xml" indent="yes"/>

<!-- Generate config file for EmuDAQ -->
  <xsl:template match="RUI-to-computer_mapping">
    <xsl:processing-instruction name="xml-stylesheet" >type="text/xml" href="XDAQConfig_XSLT.xml"</xsl:processing-instruction>
    <xsl:text>
</xsl:text>
    <xc:Partition xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
		  xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" 
		  xmlns:xc="http://xdaq.web.cern.ch/xdaq/xsd/2004/XMLConfiguration-30">
      <xsl:comment >Generated by lDAQConfigGenerator.xsl from RUI-to-computer_mapping of version <xsl:value-of select="/RUI-to-computer_mapping/@date"/></xsl:comment>

      <xsl:call-template name="i2o_protocol"/>
      <xsl:call-template name="DAQManager"/>
      <xsl:call-template name="RUIs_Monitors_and_RUs"/>
      <xsl:call-template name="BUs"/>
      <xsl:call-template name="EmuDisplayClient"/>

    </xc:Partition>
  </xsl:template>

<!-- Generate I2O protocol target id mapping -->
  <xsl:template name="i2o_protocol">
    <i2o:protocol xmlns:i2o="http://xdaq.web.cern.ch/xdaq/xsd/2004/I2OConfiguration-30">

      <xsl:for-each select="//RUI[@instance!='0' and @status = 'in']"> 
	<xsl:if test="($SIDE!='P' and $SIDE!='M') or $SIDE='B' or ($SIDE='P' and number(@instance)&lt;=18) or ($SIDE='M' and number(@instance)&gt;18)">

	  <xsl:variable name="DAQ_TID"><xsl:value-of select="3000+number(@instance)"/></xsl:variable>
	  <xsl:variable name="DQM_TID"><xsl:value-of select="1400+number(@instance)"/></xsl:variable>
	  <xsl:variable name="EVB_TID"><xsl:value-of select="1000+number(@instance)"/></xsl:variable>
	  <xsl:variable name="BU_TID" ><xsl:value-of select="1100+number(@instance)"/></xsl:variable>

	  <xsl:variable name="EVB_APP">
	    <xsl:choose>
	      <xsl:when test="@instance=$MASTERRUI">evb::EVM</xsl:when>
	      <xsl:otherwise>evb::RU</xsl:otherwise>
	    </xsl:choose>
	  </xsl:variable>

	  <i2o:target tid="{$DAQ_TID}" instance="{@instance}" class="emu::ldaq::rui::Application"></i2o:target>
	  <i2o:target tid="{$DQM_TID}" instance="{@instance}" class="EmuMonitor"></i2o:target>
	  <xsl:if test="$BUILD='Y'">
	    <i2o:target tid="{$EVB_TID}" instance="{@instance}" class="{$EVB_APP}"></i2o:target>
	    <!-- One BU on each host -->
	    <!-- Note that one of the machines hosts 2 plus and 2 minus side RUIs. The following conditional will be true once for every machine, assuming the RUIs are listed in neat ascending order of instance. -->
	    <xsl:if test="($SIDE='P' and count(preceding-sibling::RUI[@status='in'])=0) or ($SIDE='M' and count(following-sibling::RUI[@status='in'])=0) or (($SIDE!='P' and $SIDE!='M') and count(following-sibling::RUI[@status='in'])=0)">
	      <i2o:target tid="{$BU_TID}" instance="{@instance}" class="evb::BU"></i2o:target>
	    </xsl:if>
	  </xsl:if>

	</xsl:if>
      </xsl:for-each>
    </i2o:protocol>
  </xsl:template>

<!-- Generate contexts for emu::ldaq::manager -->
  <xsl:template name="DAQManager">
    <xsl:comment>emu::ldaq::manager</xsl:comment>
    <xsl:variable name="HTTP_PORT">20200</xsl:variable>
    <xc:Context url="http://csc-daq00.cms:{$HTTP_PORT}">
    <!-- <xc:Context url="http://localhost:{$HTTP_PORT}"> -->
    <!-- <xc:Context url="http://srv-c2d08-25-01.cms:{$HTTP_PORT}"> -->
      <xc:Application instance="0" class="emu::ldaq::manager::Application" network="local" id="12" service="emudaqmanager">
	<app:properties xsi:type="soapenc:Struct" xmlns:app="urn:xdaq-application:emu::ldaq::manager::Application">
	  <app:runTypes xsi:type="soapenc:Array" soapenc:arrayType="xsd:ur-type[11]">
	    <app:item xsi:type="xsd:string" soapenc:position="[0]">Monitor</app:item>
	    <app:item xsi:type="xsd:string" soapenc:position="[1]">Calib_CFEB_SCAPed</app:item>
	    <app:item xsi:type="xsd:string" soapenc:position="[2]">Calib_CFEB_Comparator</app:item>
	    <app:item xsi:type="xsd:string" soapenc:position="[3]">Calib_CFEB_CrossTalk</app:item>
	    <app:item xsi:type="xsd:string" soapenc:position="[4]">Calib_CFEB_Gains</app:item>
	    <app:item xsi:type="xsd:string" soapenc:position="[5]">Calib_ALCT_Connectivity</app:item>
	    <app:item xsi:type="xsd:string" soapenc:position="[6]">Calib_ALCT_Thresholds</app:item>
	    <app:item xsi:type="xsd:string" soapenc:position="[7]">Calib_ALCT_Delays</app:item>
	    <app:item xsi:type="xsd:string" soapenc:position="[8]">HV_Scan</app:item>
	    <app:item xsi:type="xsd:string" soapenc:position="[9]">STEP</app:item>
	    <app:item xsi:type="xsd:string" soapenc:position="[10]">Debug</app:item>
	  </app:runTypes>
	  <app:buildEvents xsi:type="xsd:boolean"><xsl:if test="$BUILD='N'">false</xsl:if><xsl:if test="$BUILD='Y'">true</xsl:if></app:buildEvents>
	  <app:runType xsi:type="xsd:string">Monitor</app:runType>

	  <app:supervisedMode xsi:type="xsd:boolean">true</app:supervisedMode>
	  <app:runDbBookingCommand xsi:type="xsd:string">/usr/bin/java -jar /nfshome0/cscdaq/bin/runnumberbooker.jar</app:runDbBookingCommand>
	  <app:runDbWritingCommand xsi:type="xsd:string">/usr/bin/java -jar /nfshome0/cscdaq/bin/runinfowriter.jar</app:runDbWritingCommand>
	  <app:runDbAddress xsi:type="xsd:string">jdbc:oracle:thin:@cmsonr1-v.cms:10121/cms_rcms.cern.ch</app:runDbAddress>
	  <app:runDbUserFile xsi:type="xsd:string">/nfshome0/cscdaq/config/.runDbUser</app:runDbUserFile>
	  <app:hardwareMapping xsi:type="xsd:string">/emu/farmer/xml/RUI-to-chamber_mapping.xml</app:hardwareMapping>
	  <app:expertSystemURL xsi:type="xsd:string">http://csc-expert.cms:8080/cdw/factcollection</app:expertSystemURL>
	  <app:isFactFinderInDebugMode xsi:type="xsd:boolean">false</app:isFactFinderInDebugMode>

	</app:properties>
      </xc:Application>
      <!-- emu::base uses Xalan -->
      <xc:Module><xsl:value-of select="$XDAQLIBDIR"/>/libxalan-c.so</xc:Module>
      <xc:Module><xsl:value-of select="$XDAQLIBDIR"/>/libxalanMsg.so</xc:Module>
      <xc:Module><xsl:value-of select="$XDAQLIBDIR"/>/libsentinelutils.so</xc:Module>
      <xc:Module><xsl:value-of select="$EMULIBDIR"/>/libemusoap.so</xc:Module>
      <xc:Module><xsl:value-of select="$EMULIBDIR"/>/libemubase.so</xc:Module>
      <xc:Module><xsl:value-of select="$EMULIBDIR"/>/libemusupervisor.so</xc:Module>
      <xc:Module><xsl:value-of select="$EMULIBDIR"/>/libemuldaqmanager.so</xc:Module>
    </xc:Context>
  </xsl:template>
  
  <!-- Generate contexts for RUIs, one of which (the 'master') is to send data to the EVM, the rest to the RUs; and the EVM and RUs -->
  <xsl:template name="RUIs_Monitors_and_RUs">
    <xsl:for-each select="//RUI[@instance!='0' and @status = 'in']">
      <xsl:if test="($SIDE!='P' and $SIDE!='M') or $SIDE='B' or ($SIDE='P' and number(@instance)&lt;=18) or ($SIDE='M' and number(@instance)&gt;18)">
	
	<xsl:variable name="HOST"><xsl:value-of select="../@alias"/></xsl:variable>

	<xsl:variable name="HTTP_RUI_PORT"    ><xsl:value-of select="20200+number(@instance)"/></xsl:variable>
	<xsl:variable name="HTTP_RU_PORT"     ><xsl:value-of select="20300+number(@instance)"/></xsl:variable>
	<xsl:variable name="HTTP_MONITOR_PORT"><xsl:value-of select="20400+number(@instance)"/></xsl:variable>
	<xsl:variable name="UTCP_RUI_PORT"    ><xsl:value-of select="20500+number(@instance)"/></xsl:variable>
	<xsl:variable name="UTCP_RU_PORT"     ><xsl:value-of select="20600+number(@instance)"/></xsl:variable>
	<xsl:variable name="UTCP_MONITOR_PORT"><xsl:value-of select="20700+number(@instance)"/></xsl:variable>
	<xsl:variable name="BTCP_RUI_PORT"    ><xsl:value-of select="20800+number(@instance)"/></xsl:variable>
	<xsl:variable name="BTCP_RU_PORT"     ><xsl:value-of select="20900+number(@instance)"/></xsl:variable>

	<xsl:variable name="DAQ_TID"><xsl:value-of select="3000+number(@instance)"/></xsl:variable>

	<xsl:variable name="FED_ID"><xsl:value-of select="@fedId"/></xsl:variable>

	<xsl:comment >RUI <xsl:value-of select="@instance"/></xsl:comment>
	
	<xc:Context url="http://{$HOST}:{$HTTP_RUI_PORT}">
	  
	  <xc:Module><xsl:value-of select="$XDAQLIBDIR"/>/libtcpla.so</xc:Module>
	  
	  <xc:Module><xsl:value-of select="$XDAQLIBDIR"/>/libxdaq2rc.so</xc:Module>
	  
	  <xc:Endpoint hostname="{$HOST}" protocol="utcp" port="{$UTCP_RUI_PORT}" service="i2o" network="dqm" connectOnRequest="true"/>
	  <xc:Application class="pt::utcp::Application" id="201" instance="{@instance}" network="dqm">
            <app:properties xmlns:app="urn:xdaq-application:pt::utcp::Application" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="soapenc:Struct">
              <app:protocol xsi:type="xsd:string">utcp</app:protocol>
              <app:maxClients xsi:type="xsd:unsignedInt">9</app:maxClients>
              <app:autoConnect xsi:type="xsd:boolean">false</app:autoConnect>
              <app:ioQueueSize xsi:type="xsd:unsignedInt">65536</app:ioQueueSize>
              <app:eventQueueSize xsi:type="xsd:unsignedInt">65536</app:eventQueueSize>
              <app:maxReceiveBuffers xsi:type="xsd:unsignedInt">12</app:maxReceiveBuffers>
              <app:maxBlockSize xsi:type="xsd:unsignedInt">0x40000</app:maxBlockSize>
            </app:properties>
	  </xc:Application>
	  <xc:Module><xsl:value-of select="$XDAQLIBDIR"/>/libptutcp.so</xc:Module>
	  
	  <!-- emu::base uses Xalan -->
	  <xc:Module><xsl:value-of select="$XDAQLIBDIR"/>/libxalan-c.so</xc:Module>
	  <xc:Module><xsl:value-of select="$XDAQLIBDIR"/>/libxalanMsg.so</xc:Module>
	  <xc:Module><xsl:value-of select="$XDAQLIBDIR"/>/libsentinelutils.so</xc:Module>
	  <xc:Module><xsl:value-of select="$EMULIBDIR"/>/libemusoap.so</xc:Module>
	  <xc:Module><xsl:value-of select="$EMULIBDIR"/>/libemubase.so</xc:Module>
	  <xc:Module><xsl:value-of select="$EMULIBDIR"/>/libemuldaqreader.so</xc:Module>
	  <xc:Module><xsl:value-of select="$EMULIBDIR"/>/libemuldaqserver.so</xc:Module>
	  <xc:Module><xsl:value-of select="$EMULIBDIR"/>/libemuldaqwriter.so</xc:Module>
	  <xc:Module><xsl:value-of select="$EMULIBDIR"/>/libemuldaqrui.so</xc:Module>
	  
	  <xc:Application class="emu::ldaq::rui::Application" id="207" instance="{@instance}" network="dqm">
            <app:properties xmlns:app="urn:xdaq-application:emu::ldaq::rui::Application" xsi:type="soapenc:Struct">
              <app:sourceHost xsi:type="xsd:string"><xsl:value-of select="$HOST"/></app:sourceHost>
              <app:sourcePort xsi:type="xsd:unsignedInt"><xsl:value-of select="$BTCP_RUI_PORT"/></app:sourcePort>
              <app:destinationHost xsi:type="xsd:string"><xsl:value-of select="$HOST"/></app:destinationHost>
              <app:destinationPort xsi:type="xsd:unsignedInt"><xsl:value-of select="$BTCP_RU_PORT"/></app:destinationPort>
	      <app:passDataOnToRUBuilder xsi:type="xsd:boolean"><xsl:value-of select="$BUILD='Y'"/></app:passDataOnToRUBuilder>
              <app:inputDeviceType xsi:type="xsd:string">spy</app:inputDeviceType>
	      <app:inputDeviceName xsi:type="xsd:string">/dev/schar<xsl:value-of select="@schar"/></app:inputDeviceName>
              <app:inputDataFormat xsi:type="xsd:string">DDU</app:inputDataFormat>
              <app:pathToRUIDataOutFile xsi:type="xsd:string">/data</app:pathToRUIDataOutFile>
              <app:ruiFileSizeInMegaBytes xsi:type="xsd:unsignedLong"><xsl:if test="$WRITE='Y'">200</xsl:if>0</app:ruiFileSizeInMegaBytes>
              <app:clientsClassName xsi:type="soapenc:Array" soapenc:arrayType="xsd:ur-type[5]">
		<app:item xsi:type="xsd:string" soapenc:position="[0]">EmuMonitor</app:item>
              </app:clientsClassName>
              <app:clientsInstance xsi:type="soapenc:Array" soapenc:arrayType="xsd:ur-type[5]">
		<app:item xsi:type="xsd:unsignedInt" soapenc:position="[0]"><xsl:value-of select="@instance"/></app:item>
              </app:clientsInstance>
              <app:sendOnClientsRequestOnly xsi:type="soapenc:Array" soapenc:arrayType="xsd:ur-type[5]">
		<app:item xsi:type="xsd:boolean" soapenc:position="[0]">true</app:item>
              </app:sendOnClientsRequestOnly>
              <app:prescalingForClient xsi:type="soapenc:Array" soapenc:arrayType="xsd:ur-type[5]">
		<app:item xsi:type="xsd:unsignedLong" soapenc:position="[0]">1</app:item>
              </app:prescalingForClient>
	      <app:poolSizeForClient xsi:type="soapenc:Array" soapenc:arrayType="xsd:ur-type[5]">
		<app:item xsi:type="xsd:unsignedLong" soapenc:position="[0]">0x4000000</app:item>
	      </app:poolSizeForClient>
              <app:fileWritingRateLimitInHz xsi:type="xsd:unsignedLong">2000</app:fileWritingRateLimitInHz>
              <app:expertSystemURL xsi:type="xsd:string">http://csc-expert.cms:8080/cdw/factcollection</app:expertSystemURL>
              <app:isFactFinderInDebugMode xsi:type="xsd:boolean">false</app:isFactFinderInDebugMode>
            </app:properties>
	  </xc:Application>
	  
	</xc:Context>

	
	<xsl:comment >EmuMonitor <xsl:value-of select="@instance"/></xsl:comment>

	<xc:Context url="http://{$HOST}:{$HTTP_MONITOR_PORT}">

	  <xc:Endpoint hostname="{$HOST}" protocol="utcp" port="{$UTCP_MONITOR_PORT}" service="i2o" network="dqm" connectOnRequest="true"/>
	  <xc:Application class="pt::utcp::Application" id="201" instance="{@instance}" network="dqm">
            <app:properties xmlns:app="urn:xdaq-application:pt::utcp::Application" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="soapenc:Struct">
              <app:protocol xsi:type="xsd:string">utcp</app:protocol>
              <app:maxClients xsi:type="xsd:unsignedInt">9</app:maxClients>
              <app:autoConnect xsi:type="xsd:boolean">false</app:autoConnect>
              <app:ioQueueSize xsi:type="xsd:unsignedInt">65536</app:ioQueueSize>
              <app:eventQueueSize xsi:type="xsd:unsignedInt">65536</app:eventQueueSize>
              <app:maxReceiveBuffers xsi:type="xsd:unsignedInt">12</app:maxReceiveBuffers>
              <app:maxBlockSize xsi:type="xsd:unsignedInt">0x40000</app:maxBlockSize>
            </app:properties>
	  </xc:Application>
	  <xc:Module><xsl:value-of select="$XDAQLIBDIR"/>/libtcpla.so</xc:Module>
	  <xc:Module><xsl:value-of select="$XDAQLIBDIR"/>/libptutcp.so</xc:Module>
	  
	  <xc:Module><xsl:value-of select="$XDAQLIBDIR"/>/libxalan-c.so</xc:Module>
	  <xc:Module><xsl:value-of select="$XDAQLIBDIR"/>/libxalanMsg.so</xc:Module>
	  <xc:Module><xsl:value-of select="$EMULIBDIR"/>/libemubase.so</xc:Module>
	  <xc:Module><xsl:value-of select="$EMULIBDIR"/>/libemuldaqwriter.so</xc:Module>
	  <xc:Module><xsl:value-of select="$EMULIBDIR"/>/libemuldaqreader.so</xc:Module>
	  <xc:Application instance="{@instance}" class="EmuMonitor" id="{1400+number(@instance)}" network="dqm" group="dqm">
	    <app:properties xmlns:app="urn:xdaq-application:EmuMonitor" xsi:type="soapenc:Struct">
              <app:readoutMode xsi:type="xsd:string">external</app:readoutMode>
              <app:inputDeviceType xsi:type="xsd:string">file</app:inputDeviceType>
              <app:inputDeviceName xsi:type="xsd:string">/tmp/run_data.raw</app:inputDeviceName>
              <app:inputDataFormat xsi:type="xsd:string">DDU</app:inputDataFormat>
              <app:nEventCredits xsi:type="xsd:unsignedInt">200</app:nEventCredits>
              <app:prescalingFactor xsi:type="xsd:unsignedInt">1</app:prescalingFactor>
              <app:serversClassName xsi:type="xsd:string">emu::ldaq::rui::Application</app:serversClassName>
              <app:serverTIDs xsi:type="soapenc:Array" soapenc:arrayType="xsd:ur-type[1]">
		<app:item xsi:type="xsd:unsignedInt" soapenc:position="[0]"><xsl:value-of select="$DAQ_TID"/></app:item>
              </app:serverTIDs>
              <app:xmlCfgFile xsi:type="xsd:string">/nfshome0/cscdqm/config/emuDQMBooking.xml</app:xmlCfgFile>
              <app:xmlCanvasesCfgFile xsi:type="xsd:string">/nfshome0/cscdqm/config/emuDQMCanvases.xml</app:xmlCanvasesCfgFile>
              <app:cscMapFile xsi:type="xsd:string">/nfshome0/cscdqm/config/dqm/csc_map.txt</app:cscMapFile>
              <app:fSaveROOTFile xsi:type="xsd:boolean">true</app:fSaveROOTFile>
              <app:outputROOTFile xsi:type="xsd:string">/data/dqm/</app:outputROOTFile>
              <app:outputImagesPath xsi:type="xsd:string">/data/dqm/images/</app:outputImagesPath>
              <app:useAltFileReader xsi:type="xsd:boolean">false</app:useAltFileReader>
              <app:dduCheckMask xsi:type="xsd:unsignedInt">0xFFFFDFFF</app:dduCheckMask>
              <app:binCheckMask xsi:type="xsd:unsignedInt">0x16EBF7F6</app:binCheckMask>
	      <app:fCheckMapping xsi:type="xsd:boolean">true</app:fCheckMapping>
	      <app:enableDataWrite xsi:type="xsd:boolean">true</app:enableDataWrite>
	      <app:maxSavedEvents xsi:type="xsd:integer">5000</app:maxSavedEvents>
	      <app:outputDataFile xsi:type="xsd:string">/data/dqm</app:outputDataFile>
	    </app:properties>
	  </xc:Application>
	  <xc:Module><xsl:value-of select="$EMULIBDIR"/>/libemudqmcscanalyzer.so</xc:Module>
	  <xc:Module><xsl:value-of select="$EMULIBDIR"/>/libemudqmcscmonitor.so</xc:Module>
	</xc:Context>


	<xsl:if test="$BUILD='Y'">

	  <xsl:variable name="EVB_APP">
	    <xsl:choose>
	      <xsl:when test="@instance=$MASTERRUI">evb::EVM</xsl:when>
	      <xsl:otherwise>evb::RU</xsl:otherwise>
	    </xsl:choose>
	  </xsl:variable>
	  
	  <xsl:comment ><xsl:value-of select="$EVB_APP"/> <xsl:value-of select="@instance"/></xsl:comment>
	  
	  <xc:Context url="http://{$HOST}:{$HTTP_RU_PORT}">
	    
	    <xc:Module><xsl:value-of select="$XDAQLIBDIR"/>/libtcpla.so</xc:Module>
	    
	    <xc:Endpoint hostname="{$HOST}" network="tcp" port="{$UTCP_RU_PORT}" protocol="atcp" service="i2o" connectOnRequest="true"/>
	    <xc:Application class="pt::utcp::Application" id="201" instance="{@instance}" network="tcp">
	      <app:properties xmlns:app="urn:xdaq-application:pt::utcp::Application" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="soapenc:Struct">
		<app:protocol xsi:type="xsd:string">atcp</app:protocol>
		<app:maxClients xsi:type="xsd:unsignedInt">9</app:maxClients>
		<app:autoConnect xsi:type="xsd:boolean">false</app:autoConnect>
		<app:ioQueueSize xsi:type="xsd:unsignedInt">65536</app:ioQueueSize>
		<app:eventQueueSize xsi:type="xsd:unsignedInt">65536</app:eventQueueSize>
		<app:maxReceiveBuffers xsi:type="xsd:unsignedInt">12</app:maxReceiveBuffers>
		<app:maxBlockSize xsi:type="xsd:unsignedInt">65537</app:maxBlockSize>
	      </app:properties>
	    </xc:Application>
	    <xc:Module><xsl:value-of select="$XDAQLIBDIR"/>/libptutcp.so</xc:Module>
	    
	    <xc:Endpoint hostname="{$HOST}" maxbulksize="0x10000" network="ferol" nonblock="true" pollingCycle="1" port="{$BTCP_RU_PORT}" protocol="btcp" rcvTimeout="0" rmode="select" service="blit" singleThread="true" sndTimeout="2000"/>
	    <xc:Application class="pt::blit::Application" id="203" instance="{@instance}" network="local">
	      <app:properties xmlns:app="urn:xdaq-application:pt::blit::Application" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="soapenc:Struct">
		<app:maxClients xsi:type="xsd:unsignedInt">32</app:maxClients>
		<app:maxReceiveBuffers xsi:type="xsd:unsignedInt">128</app:maxReceiveBuffers>
		<app:maxBlockSize xsi:type="xsd:unsignedInt">0x10000</app:maxBlockSize>
	      </app:properties>
	    </xc:Application>
	    <xc:Module><xsl:value-of select="$XDAQLIBDIR"/>/libtcpla.so</xc:Module>
	    <xc:Module><xsl:value-of select="$XDAQLIBDIR"/>/libptblit.so</xc:Module>
	    
	    <xsl:choose>
	      
	      <xsl:when test="@instance=$MASTERRUI">
		<xc:Application class="evb::EVM" id="50" instance="{@instance}" network="tcp">
		  <app:properties xmlns:app="urn:xdaq-application:evb::EVM" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="soapenc:Struct">
		    <app:inputSource xsi:type="xsd:string">Socket</app:inputSource>
		    <app:fedSourceIds soapenc:arrayType="xsd:ur-type[1]" xsi:type="soapenc:Array">
		      <app:item soapenc:position="[0]" xsi:type="xsd:unsignedInt"><xsl:value-of select="$FED_ID"/></app:item>
		    </app:fedSourceIds>
		    <app:ferolSources soapenc:arrayType="xsd:ur-type[1]" xsi:type="soapenc:Array">
		      <app:item soapenc:position="[0]" xsi:type="soapenc:Struct">
			<app:fedId xsi:type="xsd:unsignedInt"><xsl:value-of select="$FED_ID"/></app:fedId>
			<app:hostname xsi:type="xsd:string"><xsl:value-of select="$HOST"/></app:hostname>
			<app:port xsi:type="xsd:unsignedInt"><xsl:value-of select="$BTCP_RUI_PORT"/></app:port>
		      </app:item>
		    </app:ferolSources>
		    <app:checkCRC xsi:type="xsd:unsignedInt">0</app:checkCRC> <!-- disable CRC check -->
		    <app:tolerateOutOfSequenceEvents xsi:type="xsd:boolean">true</app:tolerateOutOfSequenceEvents>
		  </app:properties>
		</xc:Application>
		
	      </xsl:when>
	      <xsl:otherwise>
		
		<xc:Application class="evb::RU" id="50" instance="{@instance}" network="tcp">
		  <app:properties xmlns:app="urn:xdaq-application:evb::RU" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="soapenc:Struct">
		    <app:inputSource xsi:type="xsd:string">Socket</app:inputSource>
		    <app:fedSourceIds soapenc:arrayType="xsd:ur-type[1]" xsi:type="soapenc:Array">
		      <app:item soapenc:position="[0]" xsi:type="xsd:unsignedInt"><xsl:value-of select="$FED_ID"/></app:item>
		    </app:fedSourceIds>
		    <app:ferolSources soapenc:arrayType="xsd:ur-type[1]" xsi:type="soapenc:Array">
		      <app:item soapenc:position="[0]" xsi:type="soapenc:Struct">
			<app:fedId xsi:type="xsd:unsignedInt"><xsl:value-of select="$FED_ID"/></app:fedId>
			<app:hostname xsi:type="xsd:string"><xsl:value-of select="$HOST"/></app:hostname>
			<app:port xsi:type="xsd:unsignedInt"><xsl:value-of select="$BTCP_RUI_PORT"/></app:port>
		      </app:item>
		    </app:ferolSources>
		    <app:checkCRC xsi:type="xsd:unsignedInt">0</app:checkCRC> <!-- disable CRC check -->
		    <app:tolerateOutOfSequenceEvents xsi:type="xsd:boolean">true</app:tolerateOutOfSequenceEvents>
		  </app:properties>
		</xc:Application>
	      </xsl:otherwise>
	      
	    </xsl:choose>
	    <xc:Module><xsl:value-of select="$XDAQLIBDIR"/>/libevb.so</xc:Module>
	    
	  </xc:Context>

	</xsl:if><!-- <xsl:if test="$BUILD='Y'"> -->
	
      </xsl:if><!-- <xsl:if test="($SIDE!='P' and $SIDE!='M') or $SIDE='B' or ($SIDE='P' and number(@instance)&lt;=18) or ($SIDE='M' and number(@instance)&gt;18)"> -->
    </xsl:for-each>
  </xsl:template>

  <xsl:template name="BUs">
    <xsl:if test="$BUILD='Y'">
      <xsl:for-each select="//RUI[@instance!='0' and @status = 'in']">
	<xsl:if test="($SIDE!='P' and $SIDE!='M') or $SIDE='B' or ($SIDE='P' and number(@instance)&lt;=18) or ($SIDE='M' and number(@instance)&gt;18)">
	  
	  <!-- One BU on each host -->
	  <!-- Note that one of the machines hosts 2 plus and 2 minus side RUIs. The following conditional will be true once for every machine, assuming the RUIs are listed in neat ascending order of instance. This conditional must be the same that we have in the I2O template above. -->
	  <xsl:if test="($SIDE='P' and count(preceding-sibling::RUI[@status='in'])=0) or ($SIDE='M' and count(following-sibling::RUI[@status='in'])=0) or (($SIDE!='P' and $SIDE!='M') and count(following-sibling::RUI[@status='in'])=0)">
	    
	    <xsl:variable name="HOST"><xsl:value-of select="../@alias"/></xsl:variable>
	    <xsl:variable name="HTTP_BU_PORT"><xsl:value-of select="30000+number(@instance)"/></xsl:variable>
	    <xsl:variable name="UTCP_BU_PORT"><xsl:value-of select="30100+number(@instance)"/></xsl:variable>
	    
	    <xsl:comment >BU <xsl:value-of select="@instance"/></xsl:comment>
	    
	    <xc:Context url="http://{$HOST}:{$HTTP_BU_PORT}">
	      
	      <xc:Module><xsl:value-of select="$XDAQLIBDIR"/>/libtcpla.so</xc:Module>
	      
	      <xc:Endpoint hostname="{$HOST}" network="tcp" port="{$UTCP_BU_PORT}" protocol="atcp" service="i2o" connectOnRequest="true"/>
	      <xc:Application class="pt::utcp::Application" id="201" instance="{@instance}" network="tcp">
		<app:properties xmlns:app="urn:xdaq-application:pt::utcp::Application" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="soapenc:Struct">
		  <app:protocol xsi:type="xsd:string">atcp</app:protocol>
		  <app:maxClients xsi:type="xsd:unsignedInt">9</app:maxClients>
		  <app:autoConnect xsi:type="xsd:boolean">false</app:autoConnect>
		  <app:ioQueueSize xsi:type="xsd:unsignedInt">65536</app:ioQueueSize>
		  <app:eventQueueSize xsi:type="xsd:unsignedInt">65536</app:eventQueueSize>
		  <app:maxReceiveBuffers xsi:type="xsd:unsignedInt">12</app:maxReceiveBuffers>
		  <app:maxBlockSize xsi:type="xsd:unsignedInt">65537</app:maxBlockSize>
		</app:properties>
	      </xc:Application>
	      <xc:Module><xsl:value-of select="$XDAQLIBDIR"/>/libptutcp.so</xc:Module>
	      
	      <xc:Application class="evb::BU" id="100" instance="{@instance}" network="tcp">
		<app:properties xmlns:app="urn:xdaq-application:evb::BU" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="soapenc:Struct">
		  <!-- <app:dropEventData xsi:type="xsd:boolean">true</app:dropEventData> -->
		  <app:dropEventData xsi:type="xsd:boolean">false</app:dropEventData>
		  <app:rawDataDir xsi:type="xsd:string">/data/EVB</app:rawDataDir>
		  <app:metaDataDir xsi:type="xsd:string">/data/EVB</app:metaDataDir>
		  <app:ignoreResourceSummary xsi:type="xsd:boolean">true</app:ignoreResourceSummary> <!-- not to look for metaDataDir/resourceSummaryFileName -->
		  <app:lumiSectionTimeout xsi:type="xsd:unsignedInt">0</app:lumiSectionTimeout>
		</app:properties>
	      </xc:Application>
	      <xc:Module><xsl:value-of select="$XDAQLIBDIR"/>/libevb.so</xc:Module>
	    </xc:Context>
	    
	  </xsl:if>
	</xsl:if>
      </xsl:for-each>
    </xsl:if><!-- <xsl:if test="$BUILD='Y'"> -->
  </xsl:template>
    
  <!-- Generate context for EmuDisplayClient -->
  <xsl:template name="EmuDisplayClient">
    <xsl:comment >EmuDisplayClient</xsl:comment>
    <xc:Context url="http://csc-dqm.cms:20550">
    <!-- <xc:Context url="http://localhost:20550"> -->
    <!-- <xc:Context url="http://srv-c2d08-25-01.cms:20550"> -->
      <xc:Application class="EmuDisplayClient" id="1450" instance="0" network="local">
	<app:properties xmlns:app="urn:xdaq-application:EmuDisplayClient" xsi:type="soapenc:Struct">
          <app:monitorClass xsi:type="xsd:string">EmuMonitor</app:monitorClass>
          <app:imageFormat xsi:type="xsd:string">png</app:imageFormat>
          <app:baseDir xsi:type="xsd:string">/nfshome0/cscdqm/config/cscdqm</app:baseDir>
          <app:resultsDir xsi:type="xsd:string">/data/dqm/online</app:resultsDir>
          <app:viewOnly xsi:type="xsd:boolean">false</app:viewOnly>
          <app:xmlCfgFile xsi:type="xsd:string">/nfshome0/cscdqm/config/emuDQMBooking.xml</app:xmlCfgFile>
          <app:xmlCanvasesCfgFile xsi:type="xsd:string">/nfshome0/cscdqm/config/emuDQMCanvases.xml</app:xmlCanvasesCfgFile>
          <app:cscMapFile xsi:type="xsd:string">/nfshome0/cscdqm/config/dqm/csc_map.txt</app:cscMapFile>
          <app:expertSystemURL xsi:type="xsd:string">http://csc-expert.cms:8080/cdw/factcollection</app:expertSystemURL>
          <app:isFactFinderInDebugMode xsi:type="xsd:boolean">true</app:isFactFinderInDebugMode>
          <app:useExSys xsi:type="xsd:boolean">false</app:useExSys>
	</app:properties>
      </xc:Application>
      <!-- emu::base uses Xalan -->
      <xc:Module><xsl:value-of select="$XDAQLIBDIR"/>/libxalan-c.so</xc:Module>
      <xc:Module><xsl:value-of select="$XDAQLIBDIR"/>/libxalanMsg.so</xc:Module>
      <xc:Module><xsl:value-of select="$XDAQLIBDIR"/>/libsentinelutils.so</xc:Module>
      <xc:Module><xsl:value-of select="$EMULIBDIR"/>/libemubase.so</xc:Module>
      <xc:Module><xsl:value-of select="$EMULIBDIR"/>/libemudqmcscdisplay.so</xc:Module>
    </xc:Context>
  </xsl:template>

</xsl:transform>
