executable              = condor_step2_cfg.sh
arguments               =  $(ProcId) $(ClusterId)
#arguments               = $$(($Process + 1))
#arguments               = $(value) $(ClusterId)$(ProcId)
output                  = output/condor_step2_cfg.sh.$(ClusterId).$(ProcId).out
error                   = error/condor_step2_cfg.sh.$(ClusterId).$(ProcId).err
log                     = log/condor_step2_cfg.sh.$(ClusterId).log
#requirements            = (OpSysAndVer =?= "CentOS9")
#requirements            = (OpSysAndVer =?= "CentOS7")
universe                = vanilla
#transfer_output_files   = log.txt, dt_local_shifts.csv
should_transfer_files   = YES
#when_to_transfer_output = ON_EXIT
+MaxRuntime             = 288000
notification =  Error
notify_user = yumengguo@tamu.edu
queue 1000
